# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Standard input to each files and stdout. similar to tee, write in go"
  homepage "https://github.com/hahwul/gee"
  version "1.0.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gee/releases/download/v1.0.4/gee_1.0.4_darwin_amd64.tar.gz"
      sha256 "0d606463d560f837cfc00fafb02fc40218d565a9b493a6a95b25d4b146f06083"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gee/releases/download/v1.0.4/gee_1.0.4_linux_amd64.tar.gz"
      sha256 "0d64d5f3fa51851e17ccd9776e9f98604c5cf84fd419353ddebde044e8d3a2c8"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gee/releases/download/v1.0.4/gee_1.0.4_linux_armv6.tar.gz"
      sha256 "c6d1eed0e0bef6cdfc6af7823aba4f41b6186a19026f4d778f89fd539c40059f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gee/releases/download/v1.0.4/gee_1.0.4_linux_arm64.tar.gz"
      sha256 "6a00e24c8b864d802538b4e05f1023955b2bb25a9c0fb49a818103c54308bb58"
    end
  end

  def install
    bin.install "gee"
  end

  test do
    system "#{bin}/gee -version"
  end
end
