# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Standard input to each files and stdout. similar to tee, write in go"
  homepage "https://github.com/hahwul/gee"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gee/releases/download/v1.1.1/gee_1.1.1_darwin_amd64.tar.gz"
      sha256 "e0ee266942d70eef67557b6a3731d81bae28d7ba075c00a564c1ca6bc7fcd6db"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hahwul/gee/releases/download/v1.1.1/gee_1.1.1_darwin_arm64.tar.gz"
      sha256 "0d2383d4fb32f122c01ac1c5ab7c50ba9ea0b7e1703ee9e320642806963b6ab4"

      def install
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gee/releases/download/v1.1.1/gee_1.1.1_linux_armv6.tar.gz"
      sha256 "8dde1d256dd889699ded9f325de9bc0cef07963c67fb0307715a4cae8423a432"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gee/releases/download/v1.1.1/gee_1.1.1_linux_arm64.tar.gz"
      sha256 "a87e902f3f1319b0ed95a6181144f0539b428aaeedb5d5f37767b378802d8c3a"

      def install
        bin.install "gee"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gee/releases/download/v1.1.1/gee_1.1.1_linux_amd64.tar.gz"
      sha256 "98209fc775a34ad62e33ac0f8b195275674c8cf24a5a3e4b1faab7c44227cb26"

      def install
        bin.install "gee"
      end
    end
  end

  test do
    system "#{bin}/gee -version"
  end
end
