# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Standard input to each files and stdout. similar to tee, write in go"
  homepage "https://github.com/hahwul/gee"
  version "1.1.3"

  on_macos do
    on_intel do
      url "https://github.com/hahwul/gee/releases/download/v1.1.3/gee_1.1.3_darwin_amd64.tar.gz"
      sha256 "08293cc25e72a570a4cac8f164c5e15b41c201c778ba2c79b38cad7bafa3b686"

      def install
        bin.install "gee"
      end
    end
    on_arm do
      url "https://github.com/hahwul/gee/releases/download/v1.1.3/gee_1.1.3_darwin_arm64.tar.gz"
      sha256 "1a0d2574fb121376921359fd658ed1262ab83f466d0f4462a7a0c9282ceb396f"

      def install
        bin.install "gee"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hahwul/gee/releases/download/v1.1.3/gee_1.1.3_linux_amd64.tar.gz"
        sha256 "8c3bbce661bd413b5faf3673164591e1fb50352b9275e9dcf4b30ca89e6c2b94"

        def install
          bin.install "gee"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/hahwul/gee/releases/download/v1.1.3/gee_1.1.3_linux_armv6.tar.gz"
        sha256 "66968870d837d49bcd8279f97ca1563a9842f52dafb5363d4881981831a8293e"

        def install
          bin.install "gee"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hahwul/gee/releases/download/v1.1.3/gee_1.1.3_linux_arm64.tar.gz"
        sha256 "97766f01c0afeb5b43775e6b764f28e62a0e999476bf22841e2b992f2900bf44"

        def install
          bin.install "gee"
        end
      end
    end
  end

  test do
    system "#{bin}/gee -version"
  end
end
